default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock
  host: <%= ENV['DB_HOST'] || "localhost" %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_DATABASE'] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= "#{ENV['DB_DATABASE']}_test" %>
  
integration:
  <<: *default
  
staging:
  <<: *default

production:
  <<: *default
